version: '3.4'
services:
  gitlab-runner:
    image: rbsdev/gitlab-runner
    build: .
    hostname: local-test
    deploy:
      mode: 'replicated'
      replicas: 1
      update_config:
        parallelism: 1
        delay: 2s
        failure_action: rollback
        order: start-first
    volumes:
      - ./:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./register.sh:/register.sh
    environment:
      DEBUG: $DEBUG
      GIT_SSL_NO_VERIFY: $GIT_SSL_NO_VERIFY
      GITLAB_SERVER: $GITLAB_SERVER
      GITLAB_TOKEN: $GITLAB_TOKEN
      COMMA_SEPARATED_TAGS: $COMMA_SEPARATED_TAGS
      SRC_VOLUME: $SRC_VOLUME
      DST_VOLUME: $DST_VOLUME
      http_proxy: $http_proxy
      https_proxy: $https_proxy
